AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Bookomol - PDF Book Condensing Telegram Bot

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    Environment:
      Variables:
        NODE_ENV: !Ref Environment

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
  TelegramBotToken:
    Type: String
    NoEcho: true
    Description: Telegram Bot API Token

Resources:
  # Stub Lambda Functions
  BotHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-bot-handler'
      CodeUri: ./dist/
      Handler: handlers/bot.handler
      MemorySize: 512
      Environment:
        Variables:
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
      Events:
        WebhookApi:
          Type: Api
          Properties:
            Path: /webhook/{token}
            Method: POST

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
  WebhookUrl:
    Description: Webhook URL for Telegram
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook'